export const CREATE_GROUP_REQUEST="CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS="CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL="CREATE_GROUP_FAIL";
export const CREATE_GROUP_RESET="CREATE_GROUP_RESET";

export const UPDATE_GROUP_REQUEST="UPDATE_GROUP_REQUEST";
export const UPDATE_GROUP_SUCCESS="UPDATE_GROUP_SUCCESS";
export const UPDATE_GROUP_FAIL="UPDATE_GROUP_FAIL";
export const UPDATE_GROUP_RESET="UPDATE_GROUP_RESET";

export const ALL_GROUP_REQUEST="ALL_GROUP_REQUEST";
export const ALL_GROUP_SUCCESS="ALL_GROUP_SUCCESS";
export const ALL_GROUP_FAIL="ALL_GROUP_FAIL";

export const SEND_MESSAGE_REQUEST="SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS="SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL="SEND_MESSAGE_FAIL";
export const SEND_MESSAGE_RESET="SEND_MESSAGE_RESET";

export const GET_ALL_MESSAGES_REQUEST="GET_ALL_MESSAGES_REQUEST";
export const GET_ALL_MESSAGES_SUCCESS="GET_ALL_MESSAGES_SUCCESS";
export const GET_ALL_MESSAGES_FAIL="GET_ALL_MESSAGES_FAIL";

export const UPDATE_GROUP_ROLE_REQUEST="UPDATE_GROUP_ROLE_REQUEST";
export const UPDATE_GROUP_ROLE_SUCCESS="UPDATE_GROUP_ROLE_SUCCESS";
export const UPDATE_GROUP_ROLE_FAIL="UPDATE_GROUP_ROLE_FAIL";
export const UPDATE_GROUP_ROLE_RESET="UPDATE_GROUP_ROLE_RESET";

export const ACCEPT_REJECT_REQUEST="ACCEPT_REJECT_REQUEST";
export const ACCEPT_REJECT_SUCCESS="ACCEPT_REJECT_SUCCESS";
export const ACCEPT_REJECT_FAIL="ACCEPT_REJECT_FAIL";
export const ACCEPT_REJECT_RESET="ACCEPT_REJECT_RESET";


export const UPDATE_MEMBER_ROLE_REQUEST="UPDATE_MEMBER_ROLE_REQUEST";
export const UPDATE_MEMBER_ROLE_SUCCESS="UPDATE_MEMBER_ROLE_SUCCESS";
export const UPDATE_MEMBER_ROLE_FAIL="UPDATE_MEMBER_ROLE_FAIL";
export const UPDATE_MEMBER_ROLE_RESET="UPDATE_MEMBER_ROLE_RESET";
